# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

######################################################################
# Site Configuration Config
######################################################################

# Global Site Title
title: Get Started

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Contact Information
email: webdev@oicr.on.ca

# the subpath of your site, e.g. /blog
baseurl: ""

# Github Repository Information
git_repo: oicr-webdev/webdev_oicr-labs-pa

# Default permalink for posts
permalink: /node/:year-:month-:day-:title.html

# Post excerpt tag https://jekyllrb.com/docs/posts/#post-excerpts
excerpt_separator: "<!--more-->"

# Collections setting. https://jekyllrb.com/docs/collections/
collections:
  _modules:
  _team:
  _alumni:
  _news:
    output: false

######################################################################
# Jekyll Environment Config
######################################################################

# Build settings
markdown: kramdown

# Jekyll plugins ( also requires to add list in Gemfile )
plugins:

# Exclude these files when the site is generated.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - webpack.config.js
  - .eslint
  - package.json
  - npm-debug.log
  - vendor

theme: jekyll-theme-minimal
