<!-- footer -->
    <footer class="wrapper">
        <div class="container container-footer">
            <div class="row company-logos">
                <div class="col-xs-12 col-md-2 col-md-offset-2 oicr-logo text-center">
                    <img src="/assets/site/images/logo-ontario-institute-for-cancer-research-white.svg" alt="OICR-Logo">
                </div>
                <div class="col-xs-12 col-md-2 genome-logo text-center">
                    <img src="/assets/site/images/logo-genome-canada-white.png" alt="Genome Canada Logo">
                </div>
                <div class="col-xs-12 col-md-2 cdic-logo text-center">
                    <img src="/assets/site/images/logo-cdic-white.svg" alt="CDIC Logo">
                </div>
                <div class="col-xs-12 col-md-2 health-logo text-center">
                    <img src="/assets/site/images/logo-ontario-health-study-white.png" alt="Ontario Health Study Logo">
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-6 copy">
                    <p>&copy; Awadalla Research Laboratory 2017</p>
                </div>
                <div class="col-sm-6 policy">
                    <a href=#>Terms and Conditions</a>
                    <p>&emsp; &bull; &emsp;</p>
                    <a href=#>Policy</a>
                </div>
            </div>
        </div>
        </div>
    </footer>