<link rel="stylesheet" href="/assets/site/css/styles.css?{{ "now" | date: "%s" }}">
<link rel="stylesheet" href="/assets/site/css/pages/{{page.cssfield}}?{{ "now" | date: "%s" }}">
<link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto" rel="stylesheet">

<script>var greptchaToggle = function(){ };</script>
<script src="https://www.google.com/recaptcha/api.js?render=explicit" async defer></script>